[tool.black]
line-length = 88
target-version = ['py38']

[tool.isort]
profile = "black"
# line_length = 88
skip_gitignore = true
# atomic = true
# force_alphabetical_sort_within_sections = true
# lexicographical = true
# group_by_package = true

# eventlet is prohibited in DroidStorm
# remove_imports = eventlet

#https://bandit.readthedocs.io/en/latest/config.html
#[tool.bandit]
