---
name: Validate Pants Metadata

on:
  push:
    branches:
      # only on merges to main branch
      - main
      # and version branches, which only include minor versions (eg: v3.4)
      - v[0-9]+.[0-9]+
    tags:
      # also version tags, which include bugfix releases (eg: v3.4.0)
      - v[0-9]+.[0-9]+.[0-9]+
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      # Only for PRs targeting those branches
      - main
      - v[0-9]+.[0-9]+

jobs:
  pants-tailor:
    name: Make sure pants BUILD files are up-to-date
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # NOTE: We need to use full Python version as part of Python deps cache key otherwise
        # setup virtualenv step will fail.
        python:
          - {version-short: '3.11', version: '3.11.11'}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 'Set up Python (${{ matrix.python.version }})'
        id: python
        uses: actions/setup-python@v5
        with:
          python-version: '${{ matrix.python.version }}'

      - name: Initialize Pants and its GHA caches
        uses: ./.github/actions/init-pants
        with:
          # To ignore a bad cache, bump the cache* integer.
          gha-cache-key: cache0-BUILD

      - name: Check BUILD files
        run: |
          pants tailor --check update-build-files --check ::

      - name: Upload pants log
        uses: actions/upload-artifact@v4
        with:
          name: pants-log-py${{ matrix.python-version }}
          path: .pants.d/pants.log
        if: always()  # We want the log even on failures.
